type Mutation {
  createPost(input: CreatePostInput!): Post! @resolver(name: "create_post")
  createUser(input: CreateUserInput!): String! @resolver(name: "create_user")
  loginUser(input: LoginUserInput!): String! @resolver(name: "login_user")
}

type Query {
  communities: [Community!]!
}

type User {
  username: String! @unique
  communities: [Community!] @relation(name: "user_communities")
  posts: [Post!] @relation(name: "user_posts")
}

input CreatePostInput {
  title: String!
  message: String!
  communityId: String!
}

input CreateUserInput {
  username: String!
  password: String!
}

input LoginUserInput {
  username: String!
  password: String!
}

type Community {
  name: String!
  purpose: String
  creator: User! @relation(name: "user_communities")
  posts: [Post!] @relation(name: "community_posts")
}

type Post {
  title: String!
  message: String!
  creator: User! @relation(name: "user_posts")
  community: Community! @relation(name: "community_posts")
}